name 'puppetlabs-dhcp'
version '0.2.0'
source 'git://github.com/puppetlabs/puppetlabs-dhcp.git'
author 'puppetlabs'
license 'Apache License Version 2.0'
summary 'Manage the ISC DHCP Daemon'
description 'A Puppet module to deploy and manage the ISC DHCP server.'
project_page 'https://github.com/puppetlabs/puppet-dhcp'

dependency 'puppetlabs/stdlib', '>= 2.0.0'
dependency 'puppetlabs/concat', '>= 1.0.0'
